=== SuperLlama88888/BedrockBlockUpgradeSchema/nbt_upgrade_schema_schema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$defs": {
		"blockStateProperty": {
			"type": "object",
			"minProperties": 1,
			"maxProperties": 1,
			"additionalProperties": false,
			"properties": {
				"int": {
					"type": "integer"
				},
				"string": {
					"type": "string"
				},
				"byte": {
					"type": "integer"
				}
			}
		}
	},
	"type": "object",
	"additionalProperties": false,
	"required": [
		"maxVersionMajor",
		"maxVersionMinor",
		"maxVersionPatch",
		"maxVersionRevision"
	],
	"properties": {
		"maxVersionMajor": {
			"type": "integer",
			"minimum": 0
		},
		"maxVersionMinor": {
			"type": "integer",
			"minimum": 0
		},
		"maxVersionPatch": {
			"type": "integer",
			"minimum": 0
		},
		"maxVersionRevision": {
			"type": "integer",
			"minimum": 0
		},
		"renamedIds": {
			"type": "object",
			"additionalProperties": {
				"type": "string"
			}
		},
		"renamedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"type": "string"
				}
			}
		},
		"renamedProperties2": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"type": "string"
				}
			},
			"$comment": "propertyName -> blockName - swapped vs renamedProperties, takes less space"
		},
		"addedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"$ref": "#/$defs/blockStateProperty"
				}
			}
		},
		"addedProperties2": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"$ref": "#/$defs/blockStateProperty"
				}
			},
			"$comment": "propertyName -> blockName - swapped vs addedProperties, takes less space"
		},
		"removedProperties": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "string"
				}
			}
		},
		"removedProperties2": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "string"
				}
			},
			"$comment": "propertyName -> list of blockName - swapped vs removedProperties, takes less space"
		},
		"remappedPropertyValues": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"type": "string"
				}
			}
		},
		"remappedPropertyValues2": {
			"type": "object",
			"additionalProperties": {
				"type": "object",
				"additionalProperties": {
					"type": "string"
				}
			},
			"$comment": "propertyName -> blockName - swapped vs remappedPropertyValues, takes less space"
		},
		"remappedPropertyValuesIndex": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "object",
					"properties": {
						"old": {
							"$ref": "#/$defs/blockStateProperty"
						},
						"new": {
							"$ref": "#/$defs/blockStateProperty"
						}
					},
					"additionalProperties": false
				}
			}
		},
		"remappedStates": {
			"type": "object",
			"additionalProperties": {
				"type": "array",
				"items": {
					"type": "object",
					"required": [
						"oldState",
						"newState"
					],
					"oneOf": [
						{
							"required": ["newName"]
						},
						{
							"required": ["newFlattenedName"]
						}
					],
					"properties": {
						"oldState": {
							"type": ["object", "null"],
							"additionalProperties": {
								"$ref": "#/$defs/blockStateProperty"
							}
						},
						"newName": {
							"type": "string"
						},
						"newFlattenedName": {
							"type": "object",
							"required": [
								"prefix",
								"flattenedProperty",
								"suffix"
							],
							"properties": {
								"prefix": {
									"type": "string"
								},
								"flattenedProperty": {
									"type": "string"
								},
								"suffix": {
									"type": "string"
								}
							},
							"additionalProperties": false
						},
						"newState": {
							"type": ["object", "null"],
							"additionalProperties": {
								"$ref": "#/$defs/blockStateProperty"
							}
						},
						"copiedState": {
							"type": "array",
							"items": {
								"type": "string"
							}
						}
					},
					"additionalProperties": false
				}
			}
		}
	}
}

=== SuperLlama88888/BedrockBlockUpgradeSchema/nbt_upgrade_schema/0061_1.16.0.59_beta_to_1.16.0.68_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 16,
    "maxVersionPatch": 0,
    "maxVersionRevision": 14,
    "renamedIds": {
        "minecraft:lodestone_block": "minecraft:lodestone",
        "minecraft:twisting_vines_block": "minecraft:twisting_vines"
    },
    "addedProperties2": {
        "facing_direction": {
            "minecraft:melon_stem": {
                "int": 0
            },
            "minecraft:pumpkin_stem": {
                "int": 0
            }
        }
    },
    "removedProperties2": {
        "wall_block_type": [
            "minecraft:blackstone_wall",
            "minecraft:polished_blackstone_brick_wall",
            "minecraft:polished_blackstone_wall"
        ]
    },
    "remappedPropertyValues2": {
        "wall_block_type": {
            "minecraft:cobblestone_wall": "wall_block_type_00"
        }
    },
    "remappedPropertyValuesIndex": {
        "wall_block_type_00": [
            {
                "old": {
                    "string": "blackstone"
                },
                "new": {
                    "string": "cobblestone"
                }
            },
            {
                "old": {
                    "string": "polished_blackstone"
                },
                "new": {
                    "string": "cobblestone"
                }
            },
            {
                "old": {
                    "string": "polished_blackstone_brick"
                },
                "new": {
                    "string": "cobblestone"
                }
            }
        ]
    }
}

=== SuperLlama88888/BedrockBlockUpgradeSchema/nbt_upgrade_schema/0231_1.20.30.22_beta_to_1.20.40.24_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 20,
    "maxVersionPatch": 40,
    "maxVersionRevision": 3,
    "renamedProperties2": {
        "facing_direction": {
            "minecraft:chest": "minecraft:cardinal_direction",
            "minecraft:ender_chest": "minecraft:cardinal_direction",
            "minecraft:stonecutter_block": "minecraft:cardinal_direction",
            "minecraft:trapped_chest": "minecraft:cardinal_direction"
        }
    },
    "remappedPropertyValues2": {
        "facing_direction": {
            "minecraft:chest": "facing_direction_00",
            "minecraft:ender_chest": "facing_direction_00",
            "minecraft:stonecutter_block": "facing_direction_00",
            "minecraft:trapped_chest": "facing_direction_00"
        }
    },
    "remappedPropertyValuesIndex": {
        "facing_direction_00": [
            {
                "old": {
                    "int": 0
                },
                "new": {
                    "string": "north"
                }
            },
            {
                "old": {
                    "int": 1
                },
                "new": {
                    "string": "north"
                }
            },
            {
                "old": {
                    "int": 2
                },
                "new": {
                    "string": "north"
                }
            },
            {
                "old": {
                    "int": 3
                },
                "new": {
                    "string": "south"
                }
            },
            {
                "old": {
                    "int": 4
                },
                "new": {
                    "string": "west"
                }
            },
            {
                "old": {
                    "int": 5
                },
                "new": {
                    "string": "east"
                }
            }
        ]
    }
}

=== SuperLlama88888/BedrockBlockUpgradeSchema/nbt_upgrade_schema/0091_1.17.10_to_1.17.30.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 16,
    "maxVersionPatch": 210,
    "maxVersionRevision": 3,
    "addedProperties2": {
        "item_frame_photo_bit": {
            "minecraft:frame": {
                "byte": 0
            },
            "minecraft:glow_frame": {
                "byte": 0
            }
        }
    }
}

=== SuperLlama88888/BedrockBlockUpgradeSchema/nbt_upgrade_schema/0071_1.16.0_to_1.16.100.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 16,
    "maxVersionPatch": 0,
    "maxVersionRevision": 16,
    "addedProperties2": {
        "pillar_axis": {
            "minecraft:chain": {
                "string": "y"
            }
        }
    },
    "renamedProperties2": {
        "facing_direction": {
            "minecraft:bee_nest": "direction",
            "minecraft:beehive": "direction"
        }
    },
    "remappedPropertyValues2": {
        "facing_direction": {
            "minecraft:bee_nest": "facing_direction_00",
            "minecraft:beehive": "facing_direction_00"
        }
    },
    "remappedPropertyValuesIndex": {
        "facing_direction_00": [
            {
                "old": {
                    "int": 1
                },
                "new": {
                    "int": 0
                }
            },
            {
                "old": {
                    "int": 3
                },
                "new": {
                    "int": 0
                }
            },
            {
                "old": {
                    "int": 4
                },
                "new": {
                    "int": 1
                }
            },
            {
                "old": {
                    "int": 5
                },
                "new": {
                    "int": 3
                }
            }
        ]
    }
}

=== SuperLlama88888/BedrockBlockUpgradeSchema/nbt_upgrade_schema/0041_1.14.0_to_1.16.0.57_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 16,
    "maxVersionPatch": 0,
    "maxVersionRevision": 0,
    "addedProperties2": {
        "rotation": {
            "minecraft:jigsaw": {
                "int": 0
            }
        },
        "wall_connection_type_east": {
            "minecraft:cobblestone_wall": {
                "string": "none"
            }
        },
        "wall_connection_type_north": {
            "minecraft:cobblestone_wall": {
                "string": "none"
            }
        },
        "wall_connection_type_south": {
            "minecraft:cobblestone_wall": {
                "string": "none"
            }
        },
        "wall_connection_type_west": {
            "minecraft:cobblestone_wall": {
                "string": "none"
            }
        },
        "wall_post_bit": {
            "minecraft:cobblestone_wall": {
                "byte": 0
            }
        }
    }
}

=== SuperLlama88888/BedrockBlockUpgradeSchema/nbt_upgrade_schema/0081_1.16.200_to_1.16.210.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 16,
    "maxVersionPatch": 210,
    "maxVersionRevision": 3,
    "removedProperties2": {
        "deprecated": [
            "minecraft:stripped_crimson_hyphae",
            "minecraft:stripped_crimson_stem",
            "minecraft:stripped_warped_hyphae",
            "minecraft:stripped_warped_stem"
        ]
    }
}

=== SuperLlama88888/BedrockBlockUpgradeSchema/nbt_upgrade_schema/0011_1.10.0_to_1.12.0.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 12,
    "maxVersionPatch": 0,
    "maxVersionRevision": 1,
    "addedProperties2": {
        "direction": {
            "minecraft:campfire": {
                "int": 0
            }
        },
        "extinguished": {
            "minecraft:campfire": {
                "byte": 0
            }
        },
        "open_bit": {
            "minecraft:barrel": {
                "byte": 0
            }
        },
        "powered_bit": {
            "minecraft:lectern": {
                "byte": 0
            }
        },
        "toggle_bit": {
            "minecraft:bell": {
                "byte": 0
            }
        }
    },
    "renamedProperties2": {
        "direction": {
            "minecraft:blast_furnace": "facing_direction",
            "minecraft:coral_fan": "coral_fan_direction",
            "minecraft:coral_fan_dead": "coral_fan_direction",
            "minecraft:smoker": "facing_direction"
        },
        "fill_level": {
            "minecraft:composter": "composter_fill_level"
        }
    },
    "remappedPropertyValues2": {
        "direction": {
            "minecraft:blast_furnace": "direction_00",
            "minecraft:smoker": "direction_00"
        },
        "facing_direction": {
            "minecraft:barrel": "facing_direction_00"
        }
    },
    "remappedPropertyValuesIndex": {
        "direction_00": [
            {
                "old": {
                    "int": 0
                },
                "new": {
                    "int": 3
                }
            },
            {
                "old": {
                    "int": 1
                },
                "new": {
                    "int": 4
                }
            },
            {
                "old": {
                    "int": 3
                },
                "new": {
                    "int": 5
                }
            }
        ],
        "facing_direction_00": [
            {
                "old": {
                    "int": 6
                },
                "new": {
                    "int": 0
                }
            },
            {
                "old": {
                    "int": 7
                },
                "new": {
                    "int": 0
                }
            }
        ]
    }
}

=== SuperLlama88888/BedrockBlockUpgradeSchema/nbt_upgrade_schema/0221_1.20.20.23_beta_to_1.20.30.22_beta.json
{
    "maxVersionMajor": 1,
    "maxVersionMinor": 20,
    "maxVersionPatch": 30,
    "maxVersionRevision": 50,
    "renamedProperties2": {
        "direction": {
            "minecraft:anvil": "minecraft:cardinal_direction",
            "minecraft:big_dripleaf": "minecraft:cardinal_direction",
            "minecraft:calibrated_sculk_sensor": "minecraft:cardinal_direction",
            "minecraft:campfire": "minecraft:cardinal_direction",
            "minecraft:end_portal_frame": "minecraft:cardinal_direction",
            "minecraft:lectern": "minecraft:cardinal_direction",
            "minecraft:pink_petals": "minecraft:cardinal_direction",
            "minecraft:powered_comparator": "minecraft:cardinal_direction",
            "minecraft:powered_repeater": "minecraft:cardinal_direction",
            "minecraft:small_dripleaf_block": "minecraft:cardinal_direction",
            "minecraft:soul_campfire": "minecraft:cardinal_direction",
            "minecraft:unpowered_comparator": "minecraft:cardinal_direction",
            "minecraft:unpowered_repeater": "minecraft:cardinal_direction"
        },
        "facing_direction": {
            "minecraft:blast_furnace": "minecraft:cardinal_direction",
            "minecraft:furnace": "minecraft:cardinal_direction",
            "minecraft:lit_blast_furnace": "minecraft:cardinal_direction",
            "minecraft:lit_furnace": "minecraft:cardinal_direction",
            "minecraft:lit_smoker": "minecraft:cardinal_direction",
            "minecraft:smoker": "minecraft:cardinal_direction"
        }
    },
    "remappedPropertyValues2": {
        "direction": {
            "minecraft:anvil": "direction_00",
            "minecraft:big_dripleaf": "direction_00",
            "minecraft:calibrated_sculk_sensor": "direction_00",
            "minecraft:campfire": "direction_00",
            "minecraft:end_portal_frame": "direction_00",
            "minecraft:lectern": "direction_00",
            "minecraft:pink_petals": "direction_00",
            "minecraft:powered_comparator": "direction_00",
            "minecraft:powered_repeater": "direction_00",
            "minecraft:small_dripleaf_block": "direction_00",
            "minecraft:soul_campfire": "direction_00",
            "minecraft:unpowered_comparator": "direction_00",
            "minecraft:unpowered_repeater": "direction_00"
        },
        "facing_direction": {
            "minecraft:blast_furnace": "facing_direction_00",
            "minecraft:furnace": "facing_direction_00",
            "minecraft:lit_blast_furnace": "facing_direction_00",
            "minecraft:lit_furnace": "facing_direction_00",
            "minecraft:lit_smoker": "facing_direction_00",
            "minecraft:smoker": "facing_direction_00"
        }
    },
    "remappedPropertyValuesIndex": {
        "direction_00": [
            {
                "old": {
                    "int": 0
                },
                "new": {
                    "string": "south"
                }
            },
            {
                "old": {
                    "int": 1
                },
                "new": {
                    "string": "west"
                }
            },
            {
                "old": {
                    "int": 2
                },
                "new": {
                    "string": "north"
                }
            },
            {
                "old": {
                    "int": 3
                },
                "new": {
                    "string": "east"
                }
            }
        ],
        "facing_direction_00": [
            {
                "old": {
                    "int": 0
                },
                "new": {
                    "string": "south"
                }
            },
            {
                "old": {
                    "int": 1
                },
                "new": {
                    "string": "west"
                }
            },
            {
                "old": {
                    "int": 2
                },
                "new": {
                    "string": "north"
                }
            },
            {
                "old": {
                    "int": 3
                },
                "new": {
                    "string": "south"
                }
            },
            {
                "old": {
                    "int": 4
                },
                "new": {
                    "string": "west"
                }
            },
            {
                "old": {
                    "int": 5
                },
                "new": {
                    "string": "east"
                }
            }
        ]
    },
    "remappedStates": {
        "minecraft:concrete_powder": [
            {
                "oldState": {
                    "color": {
                        "string": "silver"
                    }
                },
                "newName": "minecraft:light_gray_concrete_powder",
                "newState": null
            },
            {
                "oldState": null,
                "newFlattenedName": {
                    "prefix": "minecraft:",
                    "flattenedProperty": "color",
                    "suffix": "_concrete_powder"
                },
                "newState": null
            }
        ],
        "minecraft:stained_hardened_clay": [
            {
                "oldState": {
                    "color": {
                        "string": "silver"
                    }
                },
                "newName": "minecraft:light_gray_terracotta",
                "newState": null
            },
            {
                "oldState": null,
                "newFlattenedName": {
                    "prefix": "minecraft:",
                    "flattenedProperty": "color",
                    "suffix": "_terracotta"
                },
                "newState": null
            }
        ]
    }
}
